site = {
"name": "StreamLive Audio",
"logo": "https://radio.ntnwb.cc/radio.png",
"channels": "amarschannels.js",
"about": "Listen to live internet radio for free, with as few advertisements as possible. Brought to you by notanewbie.",
"ipre": "IPRRE.js",
"fbimg": "https://static.thenounproject.com/png/433087-200.png",
"homeimg": "home.png",
"exploreimg": "explore.png",
"searchimg": "search.png",
"npimg": "np.png",
"playimg": "play.png",
"pauseimg": "stop.png",
"stopimg": "stop.png",
"heartimg": "heart.png",
"heartaltimg": "heartfull.png",
"shareimg": "share.png",
"menuimg": "dots.png",
"closeimg": "https://js-cdn.music.apple.com/musickit/v3/components/musickit-components/assets/icons/web-VideoPlayer-close.svg",
"infoimg": "i.png",
}
startup = {
"x": 3,
"img": "https://radio.ntnwb.cc/heartfull.png",
"header": "You'll...Like This",
"message": "Likes have been added as a beta feature! Like your favorite stations to easily find them whenever you wish. Try it out and let the developers know what you think!",
"button_text": ["Learn More", "Okay"],
"button_action": ["openLink('https://github.com/notanewbie/IPRE/issues/19')", "hideMessage()"],
"date": "6/5/22"
}
