site = {
"name": "StreamLive Audio",
"logo": "https://radio.ntnwb.cc/radio.png",
"channels": "amarschannels.js",
"about": "Listen to live internet radio for free, with as few advertisements as possible. Brought to you by notanewbie.",
"ipre": "IPRRE.js",
"fbimg": "https://static.thenounproject.com/png/433087-200.png",
"homeimg": "home.png",
"exploreimg": "explore.png",
"searchimg": "search.png",
"npimg": "np.png",
"playimg": "play.png",
"pauseimg": "stop.png",
"stopimg": "stop.png",
}